version: "3.8"

services:

  #backend:
  #  build:
  #    context: backend-pnpm/
  #    args:
  #      - PROJECT_NAME=${PROJECT_NAME}
  #      - TRANS_VERSION=${TRANS_VERSION}
  #      - APP_FOLDER=${APP_FOLDER}
  #  volumes:
  #    - ./backend-pnpm:${APP_FOLDER}
  #    - ${APP_FOLDER}/node_modules
  #  env_file:
  #    - .env
  #    - backend-pnpm/.env
  #  command: pnpm start:dev
  #  ports:
  #    - 8000:8000

  #frontend:
  #  build:
  #    context: frontend/
  #    # dockerfile: Dockerfile
  #    # target: frontend
  #    args:
  #      - PROJECT_NAME=${PROJECT_NAME}
  #      - TRANS_VERSION=${TRANS_VERSION}
  #      - APP_FOLDER=${APP_FOLDER}
  #  volumes:
  #    - ./frontend:${APP_FOLDER}
  #    - ${APP_FOLDER}/node_modules
  #  env_file:
  #    - .env
  #    - frontend/.env
  #  command: pnpm dev
  #  ports:
  #    - 3000:3000
  #    - 3101:3101

  database:
    build:
      context: database/
    container_name: transcendance_database
    restart: always
#    volumes:
#      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    env_file:
      - .env
      - database/.env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: transcendance_pgadmin
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - backend
    ports:
      - 5050:80
    restart: always

networks:
  frontend:
  backend:

volumes:
  db-data:
