def env():
    return {
        "NODE_ENV":"dev",
        "DB_HOST":"localhost",
        "DB_PORT":5432,
        "DB_USERNAME":"postgres",
        "DB_PASSWORD":"password",
        "DB_DATABASE":"postgres",
        "POSTGRES_USER":"postgres",
        "POSTGRES_PASSWORD":"password",
        "POSTGRES_DB":"postgres",
        "PGADMIN_DEFAULT_EMAIL":"test@gmail.com",
        "PGADMIN_DEFAULT_PASSWORD":"password",
        "SERVER_PORT":"8000",
        "SERVER_HOST":"localhost",
        "TOKEN_FINGERPRINT":"1234",
        "SESSION_KEY":"4321",
        "SESSION_HMAC":"5678",
        "SECRET_SIGN":"1234",
        "MAIL_USERNAME":"email",
        "MAIL_PASSWORD":"password",
        "MAIL_PORT":"port",
        "MAIL_DISPLAY":"Affichage <email>",
    }