#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${TRANS_DB_USER} WITH PASSWORD '${TRANS_DB_PASS}';
	CREATE DATABASE ${TRANS_DB_NAME} OWNER ${TRANS_DB_USER};
EOSQL
#GRANT ALL PRIVILEGES ON DATABASE ${TRANS_DB_NAME} TO ${TRANS_DB_USER};
