# Generated by Django 4.2.7 on 2023-11-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='creator_alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournament', to=settings.AUTH_USER_MODEL),
        ),
    ]
