# Generated by Django 5.0 on 2023-12-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0003_tournament_max_participants_tournament_phase_eighth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtournament',
            name='goal_average',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrationtournament',
            name='goal_conceded',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrationtournament',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TournamentRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_app.registrationtournament')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_app.tournament')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='ranking',
            field=models.ManyToManyField(related_name='tournament_ranking', through='tournament_app.TournamentRanking', to='tournament_app.registrationtournament'),
        ),
    ]
