# Generated by Django 4.2.9 on 2024-01-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0004_registrationtournament_goal_average_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='phase_eighth',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='phase_final',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='phase_pool',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='phase_quarter',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='phase_semi',
        ),
        migrations.AddField(
            model_name='tournament',
            name='phase',
            field=models.CharField(choices=[('no', 'not begin'), ('pool', 'Pool Phase'), ('eighth', 'Eighth Phase'), ('quarter', 'Quarter Phase'), ('semi', 'Semi Phase'), ('final', 'Final Phase')], default='no', max_length=10),
        ),
    ]
