# Generated by Django 4.2.8 on 2024-01-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_app', '0005_remove_tournament_phase_eighth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='phase',
            field=models.CharField(choices=[('no', 'not begin'), ('pool', 'Pool Phase'), ('eighth', 'Eighth Phase'), ('quarter', 'Quarter Phase'), ('semi', 'Semi Phase'), ('final', 'Final Phase')], default='no', max_length=20),
        ),
    ]
